
all: 
	@echo done

# Conque
all: conque.zip
conque.zip:
	wget -O $@ https://github.com/vim-scripts/Conque-Shell/archive/master.zip

# Tagbar
all: tagbar.zip
tagbar.zip:
	wget -O $@ https://github.com/majutsushi/tagbar/archive/master.zip

# NERDTree
all: nerdtree.zip
nerdtree.zip:
	wget -O $@ https://github.com/scrooloose/nerdtree/archive/master.zip

# surround
all: vim-surround.zip
vim-surround.zip:
	wget -O $@ https://github.com/tpope/vim-surround/archive/master.zip

# pathogen
all:  vim-pathogen.zip
vim-pathogen.zip:
	wget -O $@ https://github.com/tpope/vim-pathogen/archive/master.zip

# MRU
all:   mru.zip
mru.zip:
	wget -O $@ https://github.com/yegappan/mru/archive/master.zip

# markdown
all:  vim-markdown.zip
vim-markdown.zip: tabular.zip
	wget -O $@ https://github.com/plasticboy/vim-markdown/archive/master.zip

# tabular
all: tabular.zip
tabular.zip: 
	wget -O $@ https://github.com/godlygeek/tabular/archive/master.zip

# ctrlp
all: ctrlp.zip
ctrlp.zip:
	wget -O $@ https://github.com/kien/ctrlp.vim/archive/master.zip


# Can't match JavaScript inside html <script> tag
matchit.zip:
	wget -O $@ https://github.com/tmhedberg/matchit/archive/master.zip


# This plugin is now working
# headlights.zip: 
#	wget -O $@ https://github.com/mbadran/headlights/archive/master.zip

