
all: 
	@echo done

# Conque
all: conque.zip
conque.zip:
	wget -O $@ https://github.com/vim-scripts/Conque-Shell/archive/master.zip

# Tagbar
all: tagbar.zip
tagbar.zip:
	wget -O $@ https://github.com/majutsushi/tagbar/archive/master.zip

# NERDTree
all: nerdtree.zip
nerdtree.zip:
	wget -O $@ https://github.com/scrooloose/nerdtree/archive/master.zip

# surround
all: vim-surround.zip
vim-surround.zip:
	wget -O $@ https://github.com/tpope/vim-surround/archive/master.zip

# pathogen
all:  vim-pathogen.zip
vim-pathogen.zip:
	wget -O $@ https://github.com/tpope/vim-pathogen/archive/master.zip

# MRU
all:   mru.zip
mru.zip:
	wget -O $@ https://github.com/yegappan/mru/archive/master.zip

# markdown
all:  vim-markdown.zip
vim-markdown.zip: tabular.zip
	wget -O $@ https://github.com/plasticboy/vim-markdown/archive/master.zip

# tabular
all: tabular.zip
tabular.zip: 
	wget -O $@ https://github.com/godlygeek/tabular/archive/master.zip

# ctrlp
all: ctrlp.zip
ctrlp.zip:
	wget -O $@ https://github.com/kien/ctrlp.vim/archive/master.zip

# all: powerline.zip
powerline.zip:
	wget -O $@ https://github.com/powerline/powerline/archive/master.zip

all: airline.zip
airline.zip:
	wget -O $@ https://github.com/bling/vim-airline/archive/master.zip

all: accelerated-smooth-scroll.zip
accelerated-smooth-scroll.zip:
	wget -O $@ https://codeload.github.com/yonchu/accelerated-smooth-scroll/zip/master



# # https://github.com/tpope/vim-dispatch#readme
# all: vim-dispatch.zip
# vim-dispatch.zip:
# 	wget -O $@ https://github.com/tpope/vim-dispatch/archive/master.zip


# use accelerated-smooth-scroll.zip instead
# all: vim-smooth-scroll.zip
# vim-smooth-scroll.zip:
# 	wget -O $@ https://codeload.github.com/terryma/vim-smooth-scroll/zip/master

# # Rainbow Parentheses Improved
# all: rainbow.zip
# rainbow.zip:
# 	wget -O $@ https://github.com/luochen1990/rainbow/archive/master.zip

# Can't match JavaScript inside html <script> tag
matchit.zip:
	wget -O $@ https://github.com/tmhedberg/matchit/archive/master.zip


# This plugin is now working
# headlights.zip: 
#	wget -O $@ https://github.com/mbadran/headlights/archive/master.zip

